frontend/shconnector/App.js

Feat: Main 페이지 제작

---

frontend/shconnector/App.js
frontend/shconnector/package-lock.json
frontend/shconnector/package.json
frontend/shconnector/src/components/common/NavBar.js
frontend/shconnector/src/pages/Calendar/CalendarPage.js
frontend/shconnector/src/pages/Friend/FriendPage.js
frontend/shconnector/src/pages/GiftManage/GiftManagePage.js
frontend/shconnector/src/pages/ListMenu/ListMenuPage.js
frontend/shconnector/src/pages/Main/MainPage.js

1. 하단 Nav바 구현 완료
2. 추후 페이지에 따라 보이는 조건 추가 예정

Feat: 하단 nav바 구현

---

frontend/shconnector/package-lock.json
frontend/shconnector/package.json
frontend/shconnector/src/components/calendar/CalendarCustom.js
frontend/shconnector/src/pages/Calendar/CalendarPage.js
frontend/shconnector/src/reducers/CalendarSlice.js
frontend/shconnector/src/reducers/RootReducer.js

1. 커스텀 캘린더 구현
2. 색은 이후 수정예정
3. 일정 데이터는 일정페이지 구현 이후 props로 받을 수 있도록 수정예정

Feat: 달력 구현

---

frontend/shconnector/src/config/globalStyles.js

1. 글로벌 스타일 js에 색상, 화면사이즈, 폰트 계산식 작성함
2. 폰트 계산식 사용 예시
<Text style={{ fontSize: font(21) }}>일정 페이지입니다.</Text>

Feat: 글로벌 스타일.js 작성 (#23)

---

frontend/shconnector/package-lock.json
frontend/shconnector/package.json
frontend/shconnector/src/components/calendar/CalendarCustom.js
frontend/shconnector/src/components/calendar/ScheduleCard.js
frontend/shconnector/src/components/calendar/ScheduleDayList.js
frontend/shconnector/src/components/common/ButtonShort.js
frontend/shconnector/src/components/common/HorizonButton.js
frontend/shconnector/src/components/common/horizontalButton.js
frontend/shconnector/src/config/globalStyles.js
frontend/shconnector/src/pages/Calendar/CalendarPage.js

1. 일정 리스트 구현
2. 일정 리스트용 카드 컴포넌트 구현
3. 짧은 버튼 구현
4. 평행메뉴용 버튼 구현

feat: 일정 페이지 스켈레톤 구현

---

frontend/shconnector/package-lock.json
frontend/shconnector/src/components/calendar/CalendarCustom.js
frontend/shconnector/src/components/calendar/ScheduleCard.js
frontend/shconnector/src/components/calendar/ScheduleDayList.js
frontend/shconnector/src/components/common/BottomSheet.js
frontend/shconnector/src/pages/Main/MainPage.js

1. 달력 메인 페이지 스켈레톤 완성
2. 달력 일정목록 스켈레톤 완성
3. 모달용 공통 컴포넌트 스켈레톤 구현

Feat: 달력 관련 페이지 스켈레톤 코드 완성

---

frontend/shconnector/src/components/common/BottomSheet.js
frontend/shconnector/src/pages/Main/MainPage.js

Fix: 바텀시트 함수 실행 오류 디버깅 완료

---

frontend/shconnector/App.js
frontend/shconnector/package-lock.json
frontend/shconnector/src/components/calendar/CalendarCustom.js
frontend/shconnector/src/components/calendar/ScheduleDayList.js
frontend/shconnector/src/components/common/HorizonButton.js
frontend/shconnector/src/pages/Calendar/CalendarPage.js
frontend/shconnector/src/pages/ListMenu/ListMenuPage.js
frontend/shconnector/src/pages/Main/MainPage.js

CalendarCustom
ScheduleDayList
CalendarPage
ListMenuPage
CSS 수정

Fix: 페이지 별 CSS 수정

---

frontend/shconnector/App.js
frontend/shconnector/src/pages/ListMenu/ListMenuPage.js
frontend/shconnector/src/pages/Login/Login.js
frontend/shconnector/src/pages/Login/Signup.js
frontend/shconnector/src/pages/Main/MainPage.js
frontend/shconnector/src/pages/Transfer/Transfer.js

Transfer 페이지 제작,
다른 페이지들 자잘한 css 수정

Feat: 송금 페이지 제작

---

frontend/shconnector/App.js
frontend/shconnector/src/pages/Main/MainPage.js
frontend/shconnector/src/pages/Recommend/Gift.js

메인페이지에 있는 버튼 클릭 시, 해당 페이지로 이동시키기

Fix: Main페이지 버튼 클릭 시 페이지 연결

---

backend/connector/src/main/java/com/shinhan/connector/controller/ScheduleController.java
backend/connector/src/main/java/com/shinhan/connector/dto/ScheduleAddRequest.java
backend/connector/src/main/java/com/shinhan/connector/dto/ScheduleAddResponse.java
backend/connector/src/main/java/com/shinhan/connector/dto/ScheduleListResponse.java
backend/connector/src/main/java/com/shinhan/connector/dto/ScheduleResponse.java
backend/connector/src/main/java/com/shinhan/connector/repository/MyScheduleRepository.java
backend/connector/src/main/java/com/shinhan/connector/service/GiftService.java
backend/connector/src/main/java/com/shinhan/connector/service/ScheduleService.java

PR: 일정 API 세부 기능 수정

---

frontend/shconnector/package-lock.json
frontend/shconnector/package.json
frontend/shconnector/src/components/calendar/CalendarCustom.js
frontend/shconnector/src/components/calendar/ScheduleDayList.js
frontend/shconnector/src/config/globalStyles.js
frontend/shconnector/src/pages/Calendar/CalendarPage.js
frontend/shconnector/src/reducers/CalendarSlice.js
frontend/shconnector/src/util/api.js
frontend/shconnector/src/util/globalFunc.js

Feat 49 calendar data

---

frontend/shconnector/src/pages/Calendar/CalendarPage.js

Hotfix: 캘린더 머지 컨플릭스 해결 (#75)

---

frontend/shconnector/App.js
frontend/shconnector/src/pages/ListMenu/ListMenuPage.js
frontend/shconnector/src/pages/Login/Login.js
frontend/shconnector/src/pages/Main/MainPage.js
frontend/shconnector/src/pages/Recommend/Gift.js
frontend/shconnector/src/pages/Recommend/LikeSavings.js
frontend/shconnector/src/pages/Transfer/CheckAccount.js

Fix: Main페이지 로그인 전후 컴포넌트 변경

---

frontend/shconnector/App.js
frontend/shconnector/src/components/common/HeaderBar.js
frontend/shconnector/src/components/giftManage/pieChart.js
frontend/shconnector/src/pages/GiftManage/GiftAll.js
frontend/shconnector/src/pages/GiftManage/GiftGive.js
frontend/shconnector/src/pages/GiftManage/GiftManagePage.js
frontend/shconnector/src/pages/GiftManage/GiftReceived.js
frontend/shconnector/src/pages/ListMenu/ListMenuPage.js
frontend/shconnector/src/pages/Login/Signup.js

선물관리 페이지 제작
HeaderBar css 수정
회원가입  페이지 스크롤 추가
전체메뉴 경로 추가

Feat: 선물관리 페이지 제작

---

frontend/shconnector/src/pages/Login/Login.js

키보드 바깥 클릭 시 키보드 안닫히는 오류 해결
input 입력시 로그인 페이지 css 비율 오류 해결

Fix: Login 페이지 에러 수정

---

frontend/shconnector/App.js
frontend/shconnector/src/components/common/BottomSheetGift.js
frontend/shconnector/src/pages/Calendar/CalendarCreate.js
frontend/shconnector/src/pages/Friend/FriendCreatePage.js
frontend/shconnector/src/pages/GiftManage/GiftManagePage.js
frontend/shconnector/src/pages/Letter/LetterDetail.js
frontend/shconnector/src/pages/Letter/Mature.js
frontend/shconnector/src/pages/Letter/WriteLetter.js
frontend/shconnector/src/pages/Login/Signup.js

Feat: 선물 수정 모달 제작

---

frontend/shconnector/src/pages/Calendar/CalendarCreate.js
frontend/shconnector/src/pages/Friend/FriendCreatePage.js
frontend/shconnector/src/reducers/FriendSlice.js
frontend/shconnector/src/reducers/RootReducer.js

1. 지인등록 api 연결 성공
2. 일정 등록 연결 진행중 잠시 멈춤

Feat: 지인등록 api 연결 성공, 일정 등록 연결 진행중 잠시 멈춤

---

frontend/shconnector/src/pages/GiftManage/GiftGive.js

Fix: conflict 에러 해결

---

frontend/shconnector/src/pages/Calendar/CalendarCreate.js
frontend/shconnector/src/pages/Friend/FriendCreatePage.js

Feat: 일정 등록 페이지 api 연결 성공(#101)
